apiVersion: "operators.coreos.com/v1alpha1"
kind: "CatalogSource"
metadata:
  name: "redhat-marketplace"
  namespace: "openshift-marketplace"
  annotations:
    target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
spec:
  sourceType: grpc
  address: redhat-marketplace:50051
  displayName: "Red Hat Marketplace"
  publisher: "Red Hat"
  priority: -300
  updateStrategy:
    registryPoll:
      interval: 10m
