apiVersion: "operators.coreos.com/v1alpha1"
kind: "CatalogSource"
metadata:
  name: "redhat-operators"
  namespace: "openshift-marketplace"
  annotations:
    target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
spec:
  sourceType: grpc
  address: redhat-operators:50051
  displayName: "Red Hat Operators"
  publisher: "Red Hat"
  priority: -100
  updateStrategy:
    registryPoll:
      interval: 10m
