apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-operator
  labels:
    app: catalog-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: catalog-operator
  template:
    metadata:
      labels:
        app: catalog-operator
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
{{ if .RestartDate }}
        openshift.io/restartedAt: "{{ .RestartDate }}"
{{ end }}
    spec:
      volumes:
        - name: srv-cert
          secret:
            secretName: catalog-operator-serving-cert
        - name: client-ca
          secret:
            secretName: olm-client-ca
        - name: kubeconfig
          secret:
            secretName: service-network-admin-kubeconfig
      containers:
        - name: catalog-operator
          volumeMounts:
            - name: srv-cert
              mountPath: "/srv-cert"
              readOnly: true
            - name: client-ca
              mountPath: "/client-ca"
              readOnly: true
            - mountPath: /etc/openshift/kubeconfig
              name: kubeconfig
              readOnly: true
          command:
            - /bin/catalog
          args:
            - '-namespace'
            - openshift-marketplace
            - -configmapServerImage={{ imageFor "operator-registry" }}
            - -opmImage={{ imageFor "operator-registry" }}
            - -util-image
            - {{ imageFor "operator-lifecycle-manager" }}
            - -writeStatusName
            - operator-lifecycle-manager-catalog
            - --tls-cert
            - /srv-cert/tls.crt
            - --tls-key
            - /srv-cert/tls.key
            - --client-ca
            - /client-ca/tls.crt
            - -kubeconfig
            - /etc/openshift/kubeconfig/kubeconfig
          image: {{ imageFor "operator-lifecycle-manager" }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8443
              name: metrics
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8443
              scheme: HTTPS
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8443
              scheme: HTTPS
          terminationMessagePolicy: FallbackToLogsOnError
          resources:
            requests:
              cpu: 10m
              memory: 80Mi
          env:
            - name: RELEASE_VERSION
              value: {{ version "release" }}
            - name: KUBECONFIG
              value: /etc/openshift/kubeconfig/kubeconfig
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 120
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 120
      priorityClassName: hypershift-control-plane
