apiVersion: v1
kind: Service
metadata:
  name: olm-operator-metrics
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: olm-operator-serving-cert
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  labels:
    app: olm-operator
spec:
  type: ClusterIP
  ports:
    - name: https-metrics
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app: olm-operator
