apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.packages.operators.coreos.com
spec:
  caBundle: {{ .PackageServerCABundle }}
  group: packages.operators.coreos.com
  groupPriorityMinimum: 2000
  service:
    name: packageserver
    namespace: default
    port: 443
  version: v1
  versionPriority: 15
