apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: roks-metrics-push-gateway
  namespace: openshift-roks-metrics
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: http
    honorLabels: true
  selector:
    matchLabels:
      app: push-gateway
